### ISSUE TITLE
Question: Permission To add this to kenan's modpack

### ISSUE THREAD

**Issue by Theawesomeboophis** [SuddenEyePuncture/Bugs_life#2]
Hello, I would like to ( with your permission of course) add this mod to kenan's modpack found here https://github.com/Kenan2000/CDDA-Kenan-Modpack .

**Comment by SuddenEyePuncture** [comment]
Sorry for not answering for so long, I'd been busy adding this mod as a pull request to CDDA. If you want so, you can add my mod into Kenan's modpack. However you should note the mod will likely break after content freeze.

https://github.com/CleverRaven/Cataclysm-DDA/pull/49170

**Comment by Theawesomeboophis** [comment]
Okay, thanks, I'll keep that in mind, I'll probably fix it after freeze and
make sure there's no ID conflicts.
